import './js/app.js';
import './style.css';
// import './js/paysystems.json';
// import './images/americanexpress.gif';
// import './images/discovercard.gif';
// import './images/dinersclubinternational.gif';
// import './images/jcb.gif';
// import './images/mastercard.gif';
// import './images/mir.gif';
// import './images/visa.gif';
// import './images/visaelectron.gif';
// import './license.txt';
